-- Migration: Create otp_codes table for custom email OTP flow
-- This table stores OTPs generated by the send-otp edge function
-- and verified by the verify-otp edge function.

CREATE TABLE IF NOT EXISTS public.otp_codes (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email           text NOT NULL,
  otp_code        text NOT NULL,
  expires_at      timestamptz NOT NULL,
  used            boolean NOT NULL DEFAULT false,
  verify_attempts integer NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Index for fast lookup by email + used status
CREATE INDEX IF NOT EXISTS idx_otp_codes_email_used
  ON public.otp_codes (email, used, created_at DESC);

-- Auto-cleanup: delete OTP records older than 1 hour to keep the table small
-- (expired/used records are no longer needed)
CREATE OR REPLACE FUNCTION public.cleanup_expired_otps()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
AS $$
  DELETE FROM public.otp_codes
  WHERE created_at < now() - interval '1 hour';
$$;

-- RLS: only the service role (edge functions) can read/write otp_codes
ALTER TABLE public.otp_codes ENABLE ROW LEVEL SECURITY;

-- No public access — all access goes through the service-role edge functions
CREATE POLICY "No public access to otp_codes"
  ON public.otp_codes
  FOR ALL
  TO public
  USING (false);

-- Grant service role full access (edge functions use service role key)
GRANT ALL ON public.otp_codes TO service_role;

COMMENT ON TABLE public.otp_codes IS
  'Stores one-time passwords for email-based authentication. '
  'Managed exclusively by send-otp and verify-otp edge functions via service role.';
