// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { safeBrowserStorage } from "./safeStorage";
import { supabaseAuthLock } from "./supabaseAuthLock";

const SUPABASE_URL = "https://edxmwkeubdlioohxjwzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkeG13a2V1YmRsaW9vaHhqd3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2MzY2NDUsImV4cCI6MjA4MjIxMjY0NX0.iTgaTGstZIl1th7pqzIdliKo-Ek-bGxTtBU1e_bbFrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Avoid hangs in embedded/iframe contexts where localStorage or Web Locks can misbehave.
    storage: safeBrowserStorage,
    lock: supabaseAuthLock,

    persistSession: true,
    autoRefreshToken: true,
  },
});

