// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { safeBrowserStorage } from "./safeStorage";
import { supabaseAuthLock } from "./supabaseAuthLock";

const SUPABASE_URL = "https://oyvumfznbsidngombidu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95dnVtZnpuYnNpZG5nb21iaWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NDAzNTcsImV4cCI6MjA4NDMxNjM1N30.8PBc-U3IT99R5eTzI32BZvmtREek143yGcDVASG7Y4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Avoid hangs in embedded/iframe contexts where localStorage or Web Locks can misbehave.
    storage: safeBrowserStorage,
    lock: supabaseAuthLock,

    persistSession: true,
    autoRefreshToken: true,
  },
});

